SELECT
    c.person_id
  , c.member_id
  , c.year_month
  , c.payer
  , c.{{ the_tuva_project.quote_column('plan') }}
  , c.data_source
  , c.payer_attributed_provider
  , c.payer_attributed_provider_practice
  , c.payer_attributed_provider_organization
  , c.payer_attributed_provider_lob
  , c.custom_attributed_provider
  , c.custom_attributed_provider_practice
  , c.custom_attributed_provider_organization
  , c.custom_attributed_provider_lob
  , c.tuva_attributed_provider
  , c.tuva_attributed_provider_bucket
  , c.tuva_attributed_provider_specialty
  , c.inpatient_paid
  , c.outpatient_paid
  , c.office_based_paid
  , c.ancillary_paid
  , c.other_paid
  , c.pharmacy_paid
  , c.acute_inpatient_paid
  , c.ambulance_paid
  , c.ambulatory_surgery_center_paid
  , c.dialysis_paid
  , c.durable_medical_equipment_paid
  , c.emergency_department_paid
  , c.home_health_paid
  , c.inpatient_hospice_paid
  , c.inpatient_psychiatric_paid
  , c.inpatient_rehabilitation_paid
  , c.lab_paid
  , c.observation_paid
  , c.office_based_other_paid
  , c.office_based_pt_ot_st_paid
  , c.office_based_radiology_paid
  , c.office_based_surgery_paid
  , c.office_based_visit_paid
  , c.outpatient_hospice_paid
  , c.outpatient_hospital_or_clinic_paid
  , c.outpatient_pt_ot_st_paid
  , c.outpatient_psychiatric_paid
  , c.outpatient_radiology_paid
  , c.outpatient_rehabilitation_paid
  , c.outpatient_surgery_paid
  , c.skilled_nursing_paid
  , c.telehealth_visit_paid
  , c.urgent_care_paid
  , c.inpatient_allowed
  , c.outpatient_allowed
  , c.office_based_allowed
  , c.ancillary_allowed
  , c.other_allowed
  , c.pharmacy_allowed
  , c.acute_inpatient_allowed
  , c.ambulance_allowed
  , c.ambulatory_surgery_center_allowed
  , c.dialysis_allowed
  , c.durable_medical_equipment_allowed
  , c.emergency_department_allowed
  , c.home_health_allowed
  , c.inpatient_hospice_allowed
  , c.inpatient_psychiatric_allowed
  , c.inpatient_rehabilitation_allowed
  , c.lab_allowed
  , c.observation_allowed
  , c.office_based_other_allowed
  , c.office_based_pt_ot_st_allowed
  , c.office_based_radiology_allowed
  , c.office_based_surgery_allowed
  , c.office_based_visit_allowed
  , c.outpatient_hospice_allowed
  , c.outpatient_hospital_or_clinic_allowed
  , c.outpatient_pt_ot_st_allowed
  , c.outpatient_psychiatric_allowed
  , c.outpatient_radiology_allowed
  , c.outpatient_rehabilitation_allowed
  , c.outpatient_surgery_allowed
  , c.skilled_nursing_allowed
  , c.telehealth_visit_allowed
  , c.urgent_care_allowed
  , c.total_paid
  , c.medical_paid
  , c.total_allowed
  , c.medical_allowed
  , c.tuva_last_run
FROM {{ ref('the_tuva_project', 'core__cost') }} as c
